### ISSUE TITLE
Widget name with multiple spaces issue

### ISSUE THREAD

**Issue by Lindawu168** [peterzhao/dashboard#1]
A widget keeps displaying 'loading' if its name has multiple space.
For example: widget name = "gocd pipe line", the widget keeps displaying "loading" on dashboard.

**Comment by peterzhao** [comment]
the latest commit tries to fix this issue. Please verify it. Thanks

**Comment by Lindawu168** [comment]
Hi, Peter

This issue is verified on https://ju-dashboard.herokuapp.com/ site.
But on localhost:4567, this issue is still occurred.

Thanks
Linda

**Comment by peterzhao** [comment]
Hi Linda,
1. Make sure you pull the latest.
2. You may need close your browser to clean the cache.
Thanks
Peter

**Comment by Lindawu168** [comment]
The latest changes are pulled and the issue is fixed and verified on local host.
I closed this bug.

**Comment by peterzhao** [comment]
Thanks

Peter
